/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TestSerialMsg'
 * message type.
 */

public class TestSerialMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 137;

    /** Create a new TestSerialMsg of size 4. */
    public TestSerialMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TestSerialMsg of the given data_length. */
    public TestSerialMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg with the given data_length
     * and base offset.
     */
    public TestSerialMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store.
     */
    public TestSerialMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TestSerialMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TestSerialMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg embedded in the given message
     * at the given base offset.
     */
    public TestSerialMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg embedded in the given message
     * at the given base offset and length.
     */
    public TestSerialMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TestSerialMsg> \n";
      try {
        s += "  [numOfTransmission=0x"+Long.toHexString(get_numOfTransmission())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [numOfSuccess=0x"+Long.toHexString(get_numOfSuccess())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: numOfTransmission
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'numOfTransmission' is signed (false).
     */
    public static boolean isSigned_numOfTransmission() {
        return false;
    }

    /**
     * Return whether the field 'numOfTransmission' is an array (false).
     */
    public static boolean isArray_numOfTransmission() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'numOfTransmission'
     */
    public static int offset_numOfTransmission() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'numOfTransmission'
     */
    public static int offsetBits_numOfTransmission() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'numOfTransmission'
     */
    public int get_numOfTransmission() {
        return (int)getUIntBEElement(offsetBits_numOfTransmission(), 16);
    }

    /**
     * Set the value of the field 'numOfTransmission'
     */
    public void set_numOfTransmission(int value) {
        setUIntBEElement(offsetBits_numOfTransmission(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'numOfTransmission'
     */
    public static int size_numOfTransmission() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'numOfTransmission'
     */
    public static int sizeBits_numOfTransmission() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: numOfSuccess
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'numOfSuccess' is signed (false).
     */
    public static boolean isSigned_numOfSuccess() {
        return false;
    }

    /**
     * Return whether the field 'numOfSuccess' is an array (false).
     */
    public static boolean isArray_numOfSuccess() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'numOfSuccess'
     */
    public static int offset_numOfSuccess() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'numOfSuccess'
     */
    public static int offsetBits_numOfSuccess() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'numOfSuccess'
     */
    public int get_numOfSuccess() {
        return (int)getUIntBEElement(offsetBits_numOfSuccess(), 16);
    }

    /**
     * Set the value of the field 'numOfSuccess'
     */
    public void set_numOfSuccess(int value) {
        setUIntBEElement(offsetBits_numOfSuccess(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'numOfSuccess'
     */
    public static int size_numOfSuccess() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'numOfSuccess'
     */
    public static int sizeBits_numOfSuccess() {
        return 16;
    }

}
